### PR TITLE
Python rewrite

### PR DESCRIPTION
**Pull request by seanjnkns**
Complete rewrite of setup.sh and utils.sh in python, compiled as ELF-images.  Currently only supports OS_FAMILY RedHat and Debian, which encompasses ~50 different distros.

### CODE REVIEW

**Comment by seanjnkns** [comment]
Don't merge this yet.  Found a bug in the scripts auto-updater that'll cause the whole thing to stop working properly with:

IOError: [Errno 26] Text file busy: '<filename>' 

Until I find a way to fix this, please don't merge it.  Should have either a solution, or a temporary hack I can implement tomorrow.  If I have to go w/ the hacked route, it'll allow things to keep working and then when a good working auto-updater for the scripts is in place, they'll just update as they should.

The issue appeared after I swapped the SCRIPTS_URI and recompiled things.  At which point, when running the live /usr/sbin/akroma-mn-setup, it detected there was an update for itself, and attempted to update itself while it was in use.

BTW, this bug ONLY affects akroma-mn-setup/utils, and not the ability to update geth.  However, given that this error triggers earlier on in the code, it'll never reach the geth check/update portion.

**Comment by seanjnkns** [comment]
Ian, before or possibly after we shift this to a release, we'll want to figure out the SCRIPTS_URI path.  Also, we'll probably want a similar versions.json, or something, as currently each run of the setup script, it checks the GH version against the local one.  This means we're StringIO'ing the whole ~6 MB each time.  It's cached, and therefore quick, but it was/is intended to be temporary until we have a better solution in place.

**Comment by detroitpro** [comment]
IMHO: If using releases is overly complex; storing bin in source is fine..

**Comment by seanjnkns** [comment]
I'm sure being shown how to store the bin in a release once will make it so that I'll do that going forward.  I'll ask our resident kernel dev/python expert if he can show me today, otherwise Ian opted to help me tonight.

**Comment by seanjnkns** [comment]
**Contributor**
Address: 0xa2E85B0b8f7ed1569b5bBaf5aF74D07B65E0d538
Discord: seanjnkns#5616

**Pull request merged**
